### ISSUE TITLE
Accept argument separator -- in all commands

### ISSUE THREAD

**Issue by kdave** [btrfs8-revamp/btrfs8-revamp#1]
Subcommands that do not take any options, just eg. a path, do not use getopt and thus do not respect the standard "--" option separator.

**Comment by kdave** [comment]
Currently in the btrfs-progs/devel branch, scheduled for next release.

**Comment by moviuro** [comment]
Awesome @kdave !

**Comment by moviuro** [comment]
@kdave Make sure to put this requirement (*always use getopts*) in the CONTRIBUTING guidelines of btrfs-progs, if such a thing already exists.

**Comment by kdave** [comment]
Implemented long time ago.
