### ISSUE TITLE
Provide an API independent of the regular CLI UI.

### ISSUE THREAD

**Issue by Ferroin** [btrfs8-revamp/btrfs8-revamp#3]
Currently, our primary API for everything except C and C++ is the CLI UI.  This overall leads to the UI being more complicated than it needs to be for a majority of users, and also hurts efficiency.

Ideally, we should create a proper C API and then provide official bindings for other languages (at least Python, and probably also Java, Ruby, and Perl).  Once that happens, we can probably remove some of the complexity of the CLI UI (or at least hide it better from regular users) that provides no benefit to non-developers.

**Comment by kdave** [comment]
Implemented as libbtrfsutil, starting in 4.16.
