### ISSUE TITLE
Provide an option to start a balance operation asynchronously.

### ISSUE THREAD

**Issue by Ferroin** [btrfs8-revamp/btrfs8-revamp#4]
Balance operations are handled by the kernel, not userspace, but the CLI blocks until the balance completes.  The UI however implies that it's possible to run balance operations asynchronously, but the only way to do this is either though job control in a shell or using some other program that daemonizes the command.

Being able to directly start a balance asynchronously would be useful for people managing multiple filesystems, and provide better behavioral consistency with scrub, which provides an almost identical asynchronous CLI interface.

**Comment by kdave** [comment]
Agreed. The backgrounding behaviour is inconsistent, scrub/balance/dev-replace. We can enhance the ioctl interface to let kernel spawn the background task (like it's done in the post-mount balance resume). Otherwise the daemonized process should work on older kernels as a fallback.

**Comment by kdave** [comment]
Implemented in btrfs-progs v4.6.1
